import test from 'node:test';
import assert from 'node:assert/strict';
import {OFF,sample,nearestFrame,stepFrame,playbackTime,heightMeasurement,zoneBounds} from '../viewer/core.js';
function data(frames=[10,11,12]){const a=new Float32Array(161*3);for(let i=0;i<3;i++){a[i*161]=i*4.167;a[i*161+1]=frames[i];a[i*161+2]=i*10;a[i*161+OFF.q+3]=1;a[i*161+OFF.contact]=i%2;}return a;}
test('nearest and frame stepping use original samples',()=>{const a=data();assert.equal(nearestFrame(a,161,4),1);assert.equal(stepFrame(a,161,4,1),a[322]);assert.equal(stepFrame(a,161,0,-1),0);});
test('interpolate only adjacent valid markers; preserve discrete IDs/contact',()=>{const a=data(),s=sample(a,161,2);assert.ok(Math.abs(s.values[2]-4.799)<.01);assert.equal(s.values[1],10);assert.equal(s.values[OFF.contact],0);a[161+3]=NaN;assert.ok(Array.from(sample(a,161,2).values.slice(2,5)).every(Number.isNaN));});
test('source frame gaps are never bridged',()=>{const a=data([10,13,14]),s=sample(a,161,2);assert.equal(s.values[2],0);assert.equal(s.interpolated,false);});
test('paused sampling and endpoints are deterministic',()=>{const a=data();assert.equal(sample(a,161,4,false).values[1],11);assert.equal(sample(a,161,100).values[1],12);});
test('quaternion sign flips do not collapse orientation',()=>{const a=data();a[161+OFF.q+3]=-1;assert.equal(sample(a,161,2).values[OFF.q+3],1);});
test('wall clock determines playback independent of render frequency',()=>{assert.equal(playbackTime(100,1000,2000,.25,8000),350);assert.equal(playbackTime(7500,1000,2000,1,8000),8000);});
test('display distance is nonnegative; signed difference and recorded coordinates remain intact',()=>{const row=data().slice(0,161);row[4]=12;const before=row.slice();const m=heightMeasurement(row,12);assert.equal(m.height_mm,0);assert.deepEqual(row,before);row[4]=8;const below=heightMeasurement(row,12);assert.equal(below.height_mm,0);assert.equal(below.corrected_mm,-4);assert.equal(below.clamped,true);assert.equal(heightMeasurement(row,12,false).height_mm,8);row[4]=-2;assert.equal(heightMeasurement(row,null,false).height_mm,0);});
test('unknown baseline never invents zero; missing thumb hides measurement',()=>{const row=data().slice(0,161);row[4]=8;const m=heightMeasurement(row,null);assert.equal(m.calibrated,false);assert.equal(m.corrected_mm,null);assert.equal(m.height_mm,8);row[3]=NaN;assert.equal(heightMeasurement(row,8),null);});
test('zone height uses the reference transform without changing source bounds',()=>{const zone={p10:[10,20,8],p90:[30,40,20]},before=structuredClone(zone);assert.deepEqual(zoneBounds(zone,12),{min:[10,20,0],max:[30,40,8]});assert.deepEqual(zone,before);assert.deepEqual(zoneBounds(zone,12,false),{min:[10,20,8],max:[30,40,20]});assert.equal(zoneBounds(null,12),null);});
