import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),labels={READ:'阅读',WRITE:'输入',TAP:'点击',DRAG:'拖动',SCROLL_V:'竖滚',SCROLL_H:'横滚'};
const section=document.createElement('section');section.id='spatialHeat';section.innerHTML=`<h2>任务的 3D 空间热度图</h2><p>颜色表示拇指在空间格内的采样时间。旋转或缩放可观察离屏分布；高度与停留阈值跟随上方开关和滑块。</p><div class="heat-filters"><label>参与者 <select id="heatParticipant"></select></label><label>手机 <select id="heatPhone"></select></label><label>情境 <select id="heatCondition"><option value="seated">坐姿</option><option value="walking">行走</option></select></label><label>样本 <select id="heatSamples"><option value="activity">整个任务活动</option><option value="home">仅合格稳定停留</option></select></label></div><div id="heatTasks" class="heat-tasks"></div><div id="heatCanvas"></div><p id="heatInfo" role="status">读取真实样本…</p><small>手机坐标 · mm · 蓝→红为低→高（每幅图独立对数色标，跨图比较请看时间数字）。2 mm 活动体素／0.5 mm 停留体素；不平滑、不补造缺失帧。修正高度为 max(0, Z − 同记录触摸基线)，非指腹净距。</small>`;
$('reportExplorer').after(section);
const css=document.createElement('style');css.textContent='.heat-filters,.heat-tasks{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}.heat-filters label{font-size:14px}.heat-filters select,.heat-tasks button{padding:9px;border:1px solid #afc2b6;border-radius:7px;background:white;color:#245b43}.heat-tasks .active{background:#2c6650;color:white}#heatCanvas{height:460px;background:#edf2ee;border:1px solid #d4dfd5;border-radius:9px;position:relative}#heatCanvas canvas{display:block;width:100%;height:100%}#spatialHeat small{line-height:1.7;display:block}';document.head.append(css);
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf2ee');const camera=new THREE.PerspectiveCamera(38,1,.01,2000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('heatCanvas').append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;camera.position.set(155,95,230);controls.target.set(0,0,8);controls.update();
scene.add(new THREE.HemisphereLight(0xffffff,0x7f9c83,2));const root=new THREE.Group();scene.add(root);let index,task='READ',mesh,generation=0,cache=new Map();
const fetchJSON=async url=>{const target=new URL(url,location.href);target.searchParams.set('v','1.1.4');const r=await fetch(target);if(!r.ok)throw Error('数据读取失败，请重试');return r.json();};
function opts(el,items,selected){el.replaceChildren(...items.map(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;return o;}));el.value=selected;}
function resize(){const h=$('heatCanvas');renderer.setSize(h.clientWidth,h.clientHeight,false);camera.aspect=h.clientWidth/h.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('heatCanvas'));
async function draw(){
 const gen=++generation,name=`P${$('heatParticipant').value}_${$('heatPhone').value}_${$('heatCondition').value}`;$('heatInfo').textContent='读取 '+name+' '+labels[task]+'…';
 if(!cache.has(name))cache.set(name,await fetchJSON(`explorer/${name}.json`));if(gen!==generation)return;const rec=cache.get(name),td=rec.tasks[task],threshold=$('reportDwellThreshold').value,scope=$('heatSamples').value,corrected=$('reportHeightToggle').checked,choice=td?.thresholds[threshold],heat=(scope==='home'?choice?.heat:td?.activity)?.[corrected?'corrected':'raw'];
 for(const obj of [...root.children]){root.remove(obj);obj.geometry?.dispose();obj.material?.dispose();}mesh=null;
 const d=index.devices[$('heatPhone').value],[w,h,t]=d.size,[sw,sh]=d.screen,[ox,oy]=d.offset;
 const phone=new THREE.Mesh(new THREE.BoxGeometry(w,h,t),new THREE.MeshStandardMaterial({color:0x9cb4a4,transparent:true,opacity:.12,depthWrite:false}));phone.position.z=-t/2;root.add(phone);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(phone.geometry),new THREE.LineBasicMaterial({color:0x789986}));outline.position.copy(phone.position);root.add(outline);
 const screen=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.PlaneGeometry(sw,sh)),new THREE.LineBasicMaterial({color:0x446e54}));screen.position.set(w/2-ox-sw/2,h/2-oy-sh/2,0);root.add(screen);
 const axes=new THREE.AxesHelper(25);axes.position.set(w/2,h/2,0);root.add(axes);
 if(heat?.voxels.length){mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(heat.size_mm,heat.size_mm,heat.size_mm),new THREE.MeshBasicMaterial({transparent:true,opacity:.5,depthWrite:false}),heat.voxels.length);const max=Math.max(...heat.voxels.map(v=>v[3])),matrix=new THREE.Matrix4();heat.voxels.forEach((v,i)=>{const [x,y,z]=v.slice(0,3).map(a=>(a+.5)*heat.size_mm);matrix.makeTranslation(w/2-x,h/2-y,z);mesh.setMatrixAt(i,matrix);mesh.setColorAt(i,new THREE.Color().setHSL(.66*(1-Math.log1p(v[3])/Math.log1p(max)),.82,.48));});root.add(mesh);}
 $('heatInfo').textContent=`${name} · ${labels[task]} · ${scope==='home'?`停留 ≥${threshold} ms：${choice?.summary.episodes||0} 次，累计 ${((choice?.summary.total_ms||0)/1000).toFixed(3)} s`:'全任务活动'} · ${corrected?'修正离屏参考':'原始指甲 Z'} · ${heat?`${heat.valid_frames.toLocaleString()} 有效帧，${heat.voxels.length} 格；最大 ${heat.max_s.toFixed(3)} s/格`:td?'无可用触摸基线':'此任务无有效记录'}${heat&&!heat.valid_frames?' · 未检出合格停留，无热度区域':''} · 来源 ${rec.source}${rec.phone_pose_repair?' · 手机位姿已由五个自身标记点重估（留出点 P95 偏差 0.36mm），未平移手部样本':''}`;
 window.reportHeat.current={record:name,task,scope,corrected,threshold:Number(threshold),heat,summary:choice?.summary};
}
async function init(){index=await fetchJSON('index.json');const ps=[...new Set(index.clips.map(c=>c.participant))].sort((a,b)=>a-b);opts($('heatParticipant'),ps.map(p=>[String(p),'P'+p]),'3');opts($('heatPhone'),Object.keys(index.devices).map(p=>[p,p]),'N6');for(const [t,label]of Object.entries(labels)){const b=document.createElement('button');b.textContent=label;b.dataset.task=t;b.className=t===task?'active':'';b.onclick=()=>{task=t;for(const btn of $('heatTasks').children)btn.classList.toggle('active',btn===b);draw().catch(showError);};$('heatTasks').append(b);}for(const id of ['heatParticipant','heatPhone','heatCondition','heatSamples','reportHeightToggle'])$(id).addEventListener('change',()=>draw().catch(showError));$('reportDwellThreshold').addEventListener('input',()=>draw().catch(showError));window.reportHeat={draw,scene,camera,renderer,get mesh(){return mesh;}};await draw();}
function showError(e){$('heatInfo').textContent=e.message;}
function tick(){controls.update();renderer.render(scene,camera);requestAnimationFrame(tick);}tick();init().catch(showError);
